# Set this to true in order to pause the subtitling when your in-game microphone is muted
FollowMicMute: false

# Change this to your language if you don't want to speak english
CapturedLanguage: "en-US"